version: "3"

networks:
  nodenet:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - nodenet
    volumes:
      - ./:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8084:80

  node:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    container_name: node
    depends_on:
      - mysql
    networks:
      - nodenet
    volumes:
      - ./:/app
    working_dir: /app
    command: node index.js
    ports:
      - 3005:3000

  mysql:
    image: arm64v8/mysql:8.1.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - nodenet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node
      MYSQL_USER: node
      MYSQL_PASSWORD: node
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3308:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - nodenet
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8090:80
